@startuml "Теплый дом - As-Is"

!include ../C4-lib/C4_Context.puml


scale max 1200 width
skinparam dpi 100

title "Диаграмма контекста системы "Теплый дом" - As-Is"

Person(user, "Пользователь", "Пользователь системы, который хочет управлять отоплением в своем доме")
Person(technician, "Технический специалист", "Устанавливает и настраивает оборудование")

System(smart_home_system, "Умный дом", "Монолитное приложение на Go для управления отоплением и мониторинга температуры")

System_Ext(temperature_sensor, "Датчик температуры", "Устройство, которое измеряет текущую температуру в помещении")
System_Ext(heating_device, "Устройство отопления", "Реле, которое управляет системой отопления в доме")

Rel(user, smart_home_system, "Просматривает текущую температуру и управляет отоплением через", "Веб-интерфейс")
Rel(technician, smart_home_system, "Устанавливает и настраивает систему", "Физическое подключение")

Rel(smart_home_system, temperature_sensor, "Запрашивает текущую температуру", "Синхронный запрос")
Rel(smart_home_system, heating_device, "Отправляет команды включения/выключения", "Синхронный запрос")

Rel_Back(temperature_sensor, smart_home_system, "Отправляет данные о температуре", "Синхронный ответ")
Rel_Back(heating_device, smart_home_system, "Подтверждает выполнение команды", "Синхронный ответ")

@enduml 